######################################################################################
#
# NKP Management Cluster Configuration File
#
######################################################################################

######################################################################################
#
# Deployment Mode: Set to TRUE if deploying inside a VPC with a Bastion inside the VPC
#
######################################################################################
export INSIDE_VPC='FALSE'

################################################################################
#
# NKP Binaries and Bundles
#
################################################################################
export NKP_NONAIRGAPPED_DIR="${HOME}/non-air-gapped-executable/"
export NKP_DIRECTORY="${HOME}/nkp-v2.17.1/"
export NKP_BUNDLES="${NKP_DIRECTORY}/container-images/kommander-image-bundle-v2.17.1.tar,${NKP_DIRECTORY}/container-images/konvoy-image-bundle-v2.17.1.tar"

################################################################################
#
# Nutanix Infrastructure Details
#
################################################################################
export HPOC_CLUSTER='BLR-POC226'
export PRISMCENTRAL_ENDPOINT='10.136.226.7'
export NUTANIX_USER='admin'
export NUTANIX_PASSWORD='nx2Tech090!' # Ensure this matches your PC credentials

################################################################################
#
# Cluster Metadata and Hardware
#
################################################################################
export NKPCLUSTER_NAME='practice1'
export VM_IMAGE_NAME='nkp-ubuntu-24.04-release-cis-1.34.3-20260504025514'
export CSI_STORAGE_CONTAINER='nkp-spoke1'
export PC_PROJECT='nkp'

################################################################################
#
# NKP Management Server API Server IP address (IP address should be IP INSIDE VPC)
#
################################################################################
export NKPAPISERVER_VIP='1.1.1.17'       # Internal VIP for VPC or cluster VIP for no-VPC

################################################################################
#
# This value needs to be change!
# It must reflect the assigned external subnet Floating IP assigned to
# the NKP management cluster API Server
#
################################################################################
#export FloatingIP_APIServer='10.136.226.196' # External Floating IP for VPC access

################################################################################
#
# NKP Management Server Load Balancer Range (IP address range should be INSIDE VPC)
#
################################################################################
export LOAD_BALANCER_IP_RANGE='1.1.1.20-1.1.1.30'

################################################################################
#
# This value needs to be change!
# It must reflect the assigned external subnet Floating IP assigned to
# the FIRST IP of the NKP management cluster Load Balancer range
#
################################################################################
#export FloatingIP_LBFirstIP='10.136.226.217' # External IP assigned to LB range

################################################################################
#
# The VPC subnet that the NKP managment cluster is to be installed in
# Must be the same VPC that the Bastion host is in
#
################################################################################
export VPC_CONTROLPLANE_SUBNET='Spoke1_Subnet1'
export VPC_WORKER_SUBNET='Spoke1_Subnet1'

################################################################################
#
# Categories for Organization
#
################################################################################
export CONTROLPLANE_PC_CATEGORIES='Environment=Dev,nodetype=controlplane,clustertype=management'
export WORKERNODE_PC_CATEGORIES='Environment=Dev,nodetype=worker,clustertype=management'
