#####################################################################################
#
# Date			Changes
# ----			--------
# 29th July 2025	Creation
#
#####################################################################################

#####################################################################################
#
#####################################################################################

export NKP_DIRECTORY="${HOME}/nkp-v2.17.0/"

#####################################################################################
#
# Directory to locate NDK (procedure not yet documented)
#
#####################################################################################

#export NDK_DIRECTORY="${HOME}/ndk-1.3.0/"

#####################################################################################
#
# Prism Central credentials
#
#####################################################################################

export NUTANIX_USER='admin'
export NUTANIX_PASSWORD='nx2Tech274!'
export NUTANIX_PORT=9440

#####################################################################################
#
# This portion not used
# But we will leave it here as I intend to use it in the future
#
#####################################################################################

export LOCAL_REGISTRY='https://10.10.2.14:5000'
#export MIRROR_REGISTRY='https://mirror.gcr.io'

######################################################################################
#
# The variables in this section customized by me
# The variables here are NOT in official documentation
#
######################################################################################

# This is the name to give the new NKP management Cluster
export NKPCLUSTER_NAME='workload1'

# This is the name of the HPOC AHV Cluster onto which you are installing the NKP
# management cluster
export HPOC_CLUSTER='BLR-POC228'

# PRISM CENTRAL ENDPOINT
export PRISMCENTRAL_ENDPOINT='10.136.228.7'

# New NKP Management Cluster API Server VIP
# This is the floating IP of the NKP Management server's API Server
# This should be an IP inside of the VPC
export NKPAPISERVER_VIP='10.10.2.37'

# Namespace of the new workspace
export WORKSPACE_NAMESPACE='finance-nj6h8-kcfct'

# Name of subnet INSIDE the VPC
export VPC_CONTROLPLANE_SUBNET='vpc1-subnet1'
export VPC_WORKER_SUBNET='vpc1-subnet1'

# Floating IP that is assigned to the NKP management server 
# IP
export FloatingIP_APIServer='10.136.228.185'

# AOS Storage Container to house the Control Plane and Worker nodes VM
export CSI_STORAGE_CONTAINER='nkp-vpc1'

# Prism Central Project
export PC_PROJECT='nkp'

# Load Balancer IP Range
# This should be an IP range inside of the VPC
# This IP range must NOT belong to a range managed by IPAM
# Be careful here!
export LOAD_BALANCER_IP_RANGE='10.10.2.40-10.10.2.50'

# Load Balancer Floating IP that is assigned to the first IP
# in the LB IP range
export FloatingIP_LBFirstIP='10.136.228.209'

# Control Plane and Worker Node image name
# Ensure you remove the qcow2 extension
export VM_IMAGE_NAME='nkp-ubuntu-24.04-release-cis-1.34.1-20251206061851'

#
######################################################################################

