apiVersion: dataservices.nutanix.com/v1alpha1
kind: ApplicationSnapshot
metadata:
  name: shopping-app-snap-1
  namespace: shopping-demo
spec:
  expiresAfter: 24h
  source:
    applicationRef:
      name: shopping-app
