apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nutanix-charts
  # Put this in the kommander namespace so it's globally visible
  namespace: kommander
spec:
  interval: 5m
  url: https://nutanix.github.io/helm-charts
