apiVersion: v1
kind: Namespace
metadata:
  name: partner-demo
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: partner-demo
type: Opaque
stringData:
  ROOT_PASSWORD: "SuperSecretPassword123!"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: partner-demo
data:
  my.cnf: |
    [mysqld]
    max_connections = 250
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: partner-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Omitting storageClassName automatically uses your default Nutanix StorageClass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: partner-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: ROOT_PASSWORD
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: config-volume
          mountPath: /etc/mysql/conf.d
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: config-volume
        configMap:
          name: mysql-config
