#####################################################################################
#
# Date			Changes
# ----			--------
# 29th July 2025	Creation
#
#####################################################################################

#####################################################################################
#
#####################################################################################

export NKP_DIRECTORY="${HOME}/nkp-v2.17.0/"

#####################################################################################
#
# Prism Central credentials
#
#####################################################################################

export NUTANIX_USER='admin'
export NUTANIX_PASSWORD='nx2Tech284!'
export NUTANIX_PORT=9440

#####################################################################################
#
# This portion not used
# But we will leave it here as I intend to use it in the future
#
#####################################################################################

export LOCAL_REGISTRY='https://10.55.80.14:5000' # Should be bastion host IP
#export MIRROR_REGISTRY='https://mirror.gcr.io'

######################################################################################
#
# The variables in this section customized by me
# The variables here are NOT in official documentation
#
######################################################################################

# This is the name to give the new NKP management Cluster
export NKPCLUSTER_NAME='practice1'

# This is the name of the HPOC AHV Cluster onto which you are installing the NKP
# management cluster
export HPOC_CLUSTER='DM3-POC080'

# PRISM CENTRAL ENDPOINT
export PRISMCENTRAL_ENDPOINT='10.55.80.7'

# New NKP Management Cluster API Server VIP
# This is the floating IP of the NKP Management server's API Server
export NKPAPISERVER_VIP='10.55.80.17'

# AOS Storage Container to house the Control Plane and Worker nodes VM
export CSI_STORAGE_CONTAINER='nkp'

# Prism Central Project
# Thjis is the Prism Central Project that will house the NKP resources
export PC_PROJECT='nkp'

# Load Balancer IP Range
# This should be an IP range inside of the VPC
# This IP range must NOT belong to a range managed by IPAM
# Be careful here!
export LOAD_BALANCER_IP_RANGE='10.55.80.20-10.55.80.25"

# Control Plane and Worker Node image name
# Ensure you remove the qcow2 extension
export VM_IMAGE_NAME='nkp-ubuntu-24.04-release-cis-1.34.1-20251206061851'

#
######################################################################################

