#####################################################################################
#
# Date			Changes
# ------		-------
# 20th July 2025	Creation
# 23rd Nov 2025	Updated to v2.16.1
#
#####################################################################################

#####################################################################################
#
# The variables in this section customized by me
# The variables here are NOT in official documentation
#
#####################################################################################

#####################################################################################
#
# This is the directory which is the expanded directory tree from the nkp air-gapped
# tar file
# 
# This should be under your user HOME directory
#
#####################################################################################

export NKP_DIRECTORY="${HOME}/nkp-v2.16.1/"

#####################################################################################
#
#####################################################################################

export NDK_DIRECTORY="${HOME}/ndk-1.3.0/"

#####################################################################################
#
# This is the workspace in which the workload cluster will be created
# The workspace MUST first be created
#
# Do be careful. The actual namespace will have additional characters
# appeneded to the name in the initial creation of the workspace as in the example
# below
#
#####################################################################################

export WORKSPACE_NAMESPACE='partnerdemo-mnxdr-7djd9'

#####################################################################################
#
# Prism Central credentials
#
#####################################################################################

export NUTANIX_USER='admin'
export NUTANIX_PASSWORD='nx2Tech875!'
export NUTANIX_PORT=9440

#####################################################################################
#
# This is the external docker.io registry mirror
# In this case we are using the Google Container Register as the docker.io mirror
#
#####################################################################################

export MIRROR_REGISTRY='https://mirror.gcr.io'

# This is the name to give the new NKP workload cluster
export NKPCLUSTER_NAME='workload1'

# This is the name of the HPOC AHV Cluster onto which
# you are installing the NKP Workload Cluster
export HPOC_CLUSTER='PHX-POC288'

# PRISM CENTRAL ENDPOINT
export PRISMCENTRAL_ENDPOINT='10.38.60.7'

# Prism Central Project
export PC_PROJECT='nkp'

# New NKP Workload Cluster API Server VIP
export NKPAPISERVER_VIP='10.38.60.132'

# AHV Cluster subnet to use for the workload cluster
export AHV_SUBNET='aux-1'

# AOS Storage Container to house the workload cluster
# Control Plane and Worker nodes VM
export CSI_STORAGE_CONTAINER='nkp'

# Load Balancer IP Range
export LOAD_BALANCER_IP_RANGE='10.38.60.135-10.38.60.140'

# Control Plane and Worker Node image name
export VM_IMAGE_NAME='nkp-ubuntu-22.04-release-cis-1.33.5-20251108010758'

######################################################################################

